name: Test SAST Bandit action PR comment

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/bandit-check@master
